### ISSUE TITLE
Provide easy way to generate your own colors

### ISSUE THREAD

**Issue by TecHunter** [Semantic-Org/Semantic-UI-LESS#66]
Hello,

I've been using functions to generate my own color rules for components and wanted to know if it is worth to integrate it in the project via PR
Basically, I just declare my list of colors in my colors.less file:
```less
@colors:
        mred,
        red,
        pink,
        purple,
        deep-purple,
        indigo,
        blue,
        blight,
        cyan,
        teal,
        green,
        light-green,
        lime,
        yellow,
        amber,
        orange,
        deep-orange,
        brown,
        blue-grey,
        grey;

```
Then I have a mixin which loop over this list and call a .createColor for each of these:

```less
.generateColors(@mixin: false) {
  .loop(@i: length(@colors)) when (@i > 0) {
    @color: extract(@colors, @i);
    &.@{color} {
      @color-base: "@{color}-base";
      @color-base-text: "grey-lighten-5";
      @color-base-hover: "@{color}-lighten-1";

      @color-light: "@{color}-lighten-2";
      @color-light-text: "grey-lighten-5";
      @color-light-hover: "@{color}-lighten-3";

      @color-dark: "@{color}-darken-2";
      @color-dark-text: "grey-lighten-5";
      @color-dark-hover: "@{color}-base";

      .do() when (@mixin = true) {
        .createColor(@@color-base, @@color-base-text, @@color-base-hover);
        &.light {
          .createColor(@@color-light, @@color-light-text, @@color-light-hover);
        }
        &.dark{
          .createColor(@@color-dark, @@color-dark-text, @@color-dark-hover);
        }

      }

      .do() when (@mixin = false) {
        background-color: @@color-base;
        &.light {
          background-color: @@color-light;
          color: @grey-darken-4
        }

        &.dark {
          background-color: @@color-dark;
          color: @grey-lighten-5
        }
      }
      .do();

    }

    .loop((@i - 1));
  }

  .loop();
}

.color {
  .generateColors();

  &.white{
    background-color: white;
    color: @textColor;
  }
}
```

Now every components need to define its own .createColor mixin then call the generator after.
Example with labels:

```less
.labelColors(@color, @textColor, @hoverColor, @hoverTextColor) {
  .ui.labels &.label,
  &.ui.label {
    &, &.disabled:hover {
      cursor: default;
      background-color: @color !important;
      border-color: @color !important;
      color: @textColor !important;
    }
  }

  .ui.labels &.label:not(.disabled):hover,
  .ui.label a:not(.disabled) &:hover {
    cursor: pointer;
    background-color: @hoverColor !important;
    border-color: @hoverColor !important;
    color: @hoverTextColor !important;
  }
}

.createColor(@color, @textColor, @hoverColor, @hoverTextColor: lighten(@textColor, 5)) {

  .labelColors(@color, @textColor, @hoverColor, @hoverTextColor);
  &.basic {
    /* inverted for basic */
    .labelColors(white, @color, @color, @textColor);
  }

  /* Ribbon */

  &.ribbon {
    border-color: darken(@color, 7) !important;
  }
}

.generateColors(true);

```

I still have some things to fix but I hope you get the idea. please vote for this change to motivate me to PR
