### ISSUE TITLE
Bug? The list item of nested list are invisibility.

### ISSUE THREAD

**Issue by DerekHung** [Semantic-Org/Semantic-UI-LESS#70]
Hi, I found when I use <List> as following: 
```javascript

<List>
  <List.List>
      <List.Item> 123 </List.Item>
      <List.Item> 123 </List.Item>
  </List.List>
</List>
```

And all of list.item are invisibility.
I check the .less file and I found this line: 
```css
ul.ui.list > li:first-child:after,
ol.ui.list > li:first-child:after,
.ui.list > .list > .item,
.ui.list > .item:after {
  content: '';
  display: block;
  height: 0;
  clear: both;
  visibility: hidden;
}
```

It looks weird, because these css code are used to describe virtual element. 
Is this a typo ? should it be .ui.list > .list > .item:before or ?
Thanks.
